// <auto-generated />
namespace BluePumpkinn.Migrations.AnotherDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Next : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Next));
        
        string IMigrationMetadata.Id
        {
            get { return "201512030847379_Next"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
